spring:
  main:
    lazy-initialization: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    hikari:
      max-lifetime: 240000 # 4 minutes
server:
  servlet:
    session:
      cookie:
        secure: true
  error:
    include-message: never
